### ISSUE TITLE
Simplify spoken clock translation

### ISSUE THREAD

**Issue by quozl** [sugarlabs/clock-activity#14]
https://github.com/sugarlabs/clock-activity/pull/11 ended with an agreement to change the spoken time to avoid difficult to translate strings; in particular to speak the hour and minute literally, as in "eleven forty-five".

**Comment by EmilyOng** [comment]
Hello Quozl, please take a look at this :)

I have simplified the clock translation by:

```

        time(12, 0) => twelve noon |
        time(0, 0) => midnight |
        time(h, 0) => hour(h) o'clock am_pm(h) |
        time(h, m) [m < 10] => hour(h) o' min(m) am_pm(h) |
	time(h, m) [m >= 10] => hour(h) min(m) am_pm(h) |

```
1. Changing the output of time(12, 0) to twelve noon instead of hour(12), because for the sake of simplification, I have removed 'noon', 'midnight' and 'quarter' from the list of strings (Same goes for midnight)
2. I actually though that if we indicated the time as "eleven one" or "ten two", it will be rather weird. So I added a rule, where if the minute(m) is less than 10, it will read "eleven o' one" instead. How is this?
3. In addition, I removed the "minutes" in the rules.

Please let me know how this is, thank you so much!

>>Commits
https://github.com/EmilyOng/clock-activity/blob/simplify-t/test_timewriter/LANG_rules.py

>>Output
[timewriter.txt](https://github.com/sugarlabs/clock-activity/files/1552031/timewriter.txt)

**Comment by quozl** [comment]
@EmilyOng, thanks.  From discussion in #11 the intention was to substantially simplify both what is spoken and how it appears in the source code so that translators will engage using their limited tools.  They don't want to have to change source files, only `po/*.po` files.  You may have to explain your proposal to me further, 'cause I'm not very familiar with the code.

**Comment by leonardcj** [comment]
What needs to happen is to eliminate this very ugly string entry which requires insertion of all sorts of markup

https://translate.sugarlabs.org/en/Clock/translate/#filter=all&unit=960927

Basically, this needs to abandon a rotary clcck face for a digital clock readout.

**Comment by quozl** [comment]
Thanks @leonardcj, there are two issues then;

* the HTML markup, and;
* the length of the entry.

The HTML markup is for text colouring to match the colour of the clock hands or digits, and might be moved out of the translatable string and into the source code.  This will also slightly reduce the length.

The length of the entry can be further reduced by one or more of the following;

* removing the nearly duplicate `hour1` rules and instead calculate them from the `hour` rules,
* switching to smaller keywords, such as `h` instead of `hour`,
* simplifying the rules as @EmilyOng has done.

I don't think the clock face needs to change, just the way it is spoken or described by text.

@EmilyOng, you might also look around for Python library or source code that speaks a time of day; we might accept it if it has good code quality, good license, and internationalisation support using gettext.

**Comment by EmilyOng** [comment]
Thanks!

- [x] removing the nearly duplicate hour1 rules and instead calculate them from the hour rules
- [x] simplifying the rules

**Comment by quozl** [comment]
@leonarcj, this is now complete, please test.

Final `genpot` change here;
9a5451a6d0ad682d98544cd88800aa2abdd225e9
